import Enums from './enums';

export const MAX_CACHED_RESULT_COUNT = 16;

export const leading = {
  [Enums.FLEX_DIRECTION_COLUMN]: Enums.EDGE_TOP,
  [Enums.FLEX_DIRECTION_COLUMN_REVERSE]: Enums.EDGE_BOTTOM,
  [Enums.FLEX_DIRECTION_ROW]: Enums.EDGE_LEFT,
  [Enums.FLEX_DIRECTION_ROW_REVERSE]: Enums.EDGE_RIGHT,
};

export const trailing = {
  [Enums.FLEX_DIRECTION_COLUMN]: Enums.EDGE_BOTTOM,
  [Enums.FLEX_DIRECTION_COLUMN_REVERSE]: Enums.EDGE_TOP,
  [Enums.FLEX_DIRECTION_ROW]: Enums.EDGE_RIGHT,
  [Enums.FLEX_DIRECTION_ROW_REVERSE]: Enums.EDGE_LEFT,
};

export const dim = {
  [Enums.FLEX_DIRECTION_COLUMN]: Enums.DIMENSION_HEIGHT,
  [Enums.FLEX_DIRECTION_COLUMN_REVERSE]: Enums.DIMENSION_HEIGHT,
  [Enums.FLEX_DIRECTION_ROW]: Enums.DIMENSION_WIDTH,
  [Enums.FLEX_DIRECTION_ROW_REVERSE]: Enums.DIMENSION_WIDTH,
};

export const pos = {
  [Enums.FLEX_DIRECTION_COLUMN]: Enums.EDGE_TOP,
  [Enums.FLEX_DIRECTION_COLUMN_REVERSE]: Enums.EDGE_BOTTOM,
  [Enums.FLEX_DIRECTION_ROW]: Enums.EDGE_LEFT,
  [Enums.FLEX_DIRECTION_ROW_REVERSE]: Enums.EDGE_RIGHT,
};

export default {
  MAX_CACHED_RESULT_COUNT,
  leading,
  trailing,
  dim,
  pos,
};
